openapi: '3.0.3'
info:
  title: Pratikum OpenApi
  version: '1.0'
servers:
  - url: https://localhost:3000

components:
  schemas:
    user: 
      type: object 
      properties: 
        id:
          type: integer
        name: 
          type: string
        email: 
          type: string
        age: 
          type: integer
        updatedAt:
          type: string
paths:
  /users: 
    get: 
      description: 'Endpoint untuk mendapatkan semua data user'
      responses:
        '200':
          description: Berhasil
          content: 
            application/json: 
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '500':
            description: Server Gagal
        '403':
            description: Tidak diijinkan
